### ISSUE TITLE
banner-issue.sh error on second run of mv /etc/issue /etc/issue_old

### ISSUE THREAD

**Issue by adrelanos** [monsieuremre/hardened-tumbleweed#1]
https://github.com/monsieuremre/hardened-tumbleweed/blob/main/scripts/banner-issue.sh

    mv /etc/issue /etc/issue_old

This will show an error message on second run.

**Comment by monsieuremre** [comment]
Will fix.

**Comment by monsieuremre** [comment]
fixed and ready to serve
