### ISSUE TITLE
handling of re-run of scripts (idempotent) and updating of PAM settings

### ISSUE THREAD

**Issue by adrelanos** [monsieuremre/hardened-tumbleweed#2]
https://github.com/monsieuremre/hardened-tumbleweed/blob/main/scripts/pam-harden.sh

```
cp /etc/pam.d/passwd /etc/pam.d_passwd_old
cp /etc/pam.d/common-session /etc/pam.d_common-session_old
cp /etc/pam.d/system-login /etc/pam.d_system-login_old

echo "password required pam_unix.so sha512 shadow nullok rounds=65536" >> /etc/pam.d/passwd
echo "session optional pam_umask.so umask=0027
session [default=1 success=ignore] pam_succeed_if.so quiet user ingroup secret-agents
session optional pam_umask.so umask=0077" >> /etc/pam.d/common-session
echo "auth optional pam_faildelay.so delay=4000000" >> /etc/pam.d/system-login
```

I am not a fan of this style. This gets messy quickly...

It's functional rather than declarative, i.e. harder to understand.

If re-running the script, it would duplicate the config entries.

How would you handle future updates if you want to change existing lines, prepend or append new lines?

How could you know in the future which version had what settings?

**Comment by monsieuremre** [comment]
> It's functional rather than declarative, i.e. harder to understand.
>
> If re-running the script, it would duplicate the config entries.

Sir I see you are raising some very valid points. You are right it is messy.

This is more like a script and not a package. It modifies configs in etc because it is as if the admin himself is modifying them.

The double running can definetely be prevented tho, which I will do soon. But when it comes to changes, it should be removed and reapplied. I guess an update script can be made to that.

**Comment by monsieuremre** [comment]
Ok done and fixed.

> How could you know in the future which version had what settings?

Yes. So no we won't know that unfortunately just yet. I will transform this script thing into a systemd service that makes sure everything stays hardened the way they are supposed to be by getting the most current settings from this repo. When that happens, this possibility will be no more.
